<?xml version="1.0" encoding="utf-8"?><Database Name="Project_Database" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Project_Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Project_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Inv_Game" Member="Inv_Games">
    <Type Name="Inv_Game">
      <Column Name="Inv_Game_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Game_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inv_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_Inv_Game" Member="Invoice" ThisKey="Inv_Id" OtherKey="Inv_Id" Type="Invoice" IsForeignKey="true" />
      <Association Name="Game_Inv_Game" Member="Game" ThisKey="Game_Id" OtherKey="Game_Id" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USer_Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="User_FirstName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Surname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="User_Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="User_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Cellphone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="User_Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="User_ID" OtherKey="User_ID" Type="Invoice" />
      <Association Name="User_Game" Member="Games" ThisKey="User_ID" OtherKey="User_ID" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Inv_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Total_Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Shopping_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date_Logged" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_Inv_Game" Member="Inv_Games" ThisKey="Inv_Id" OtherKey="Inv_Id" Type="Inv_Game" />
      <Association Name="User_Invoice" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="Game_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Game_Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Game_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Game_Descrp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Game_Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Game_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Game_Num_Comments" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Game_Date_Added" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Game_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Game_Image" Type="System.String" DbType="VarChar(50)" CanBeNull="false" />
      <Column Name="Game_Trailer" Type="System.String" DbType="VarChar(50)" CanBeNull="false" />
      <Column Name="Game_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Discount_Percentage" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Game_Inv_Game" Member="Inv_Games" ThisKey="Game_Id" OtherKey="Game_Id" Type="Inv_Game" />
      <Association Name="User_Game" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>